spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://team-1-211129.cvtq9j4axrge.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
