FROM openjdk:8-jdk-alpine

# Copy the JAR from the target folder into the container
COPY /target/Project2-0.0.1-SNAPSHOT.jar Project2-0.0.1-SNAPSHOT.jar 

ENTRYPOINT ["java", "-jar", "/Project2-0.0.1-SNAPSHOT.jar"]